# Generated by Django 2.1.1 on 2018-09-16 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentários',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='circle',
            options={'ordering': ['id'], 'verbose_name': 'Circulo', 'verbose_name_plural': 'Circulos'},
        ),
        migrations.AddField(
            model_name='comment',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.Circle', verbose_name='Circulo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
